# Generated by Django 5.1.6 on 2025-03-29 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_prediction', models.CharField(max_length=50)),
                ('dl_prediction', models.CharField(max_length=50)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.lab')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='APP.prediction')),
            ],
        ),
        migrations.CreateModel(
            name='TestDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impulse', models.FloatField()),
                ('pressure_high', models.FloatField()),
                ('pressure_low', models.FloatField()),
                ('glucose', models.FloatField()),
                ('kcm', models.FloatField()),
                ('troponin', models.FloatField()),
                ('ecg_image', models.ImageField(blank=True, null=True, upload_to='ecg_images/')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.patient')),
            ],
            options={
                'unique_together': {('patient', 'lab')},
            },
        ),
        migrations.AddField(
            model_name='prediction',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.testdetails'),
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_tests', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.patient')),
            ],
        ),
    ]
