# Generated by Django 5.1.6 on 2025-03-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_yourbillmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yourbillmodel',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
